import React, { ReactNode } from "react";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import ProductProviders from "./provider";
import dynamic from "next/dynamic";

const PersistedReduxProvider = dynamic(() => import("../app/redux/provider"), {
  ssr: false,
});

// import  PersistedReduxProvider from "../app/redux/provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kickz",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <PersistedReduxProvider>
          <ProductProviders>
            <div className="navbar">
              <Navbar />
            </div>
            <div>{children}</div>
            <Footer />
          </ProductProviders>
        </PersistedReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
